### ISSUE TITLE
Unexpected Error Message When There Are No Matching Versions

### ISSUE THREAD

**Issue by freshleafmedia** [php/pie#117]
I tried to install `xdebug/xdebug` as is shown in the [docs](https://github.com/php/pie/blob/e4b1fd111b72fafcdf9512d9a009cb54742eb72c/docs/usage.md#downloading-building-or-installing-an-extension) and `xdebug/xdebug:^3.4` as is shown in the CLI example but received the message:

![20241119-1729](https://github.com/user-attachments/assets/8714920a-4e8b-4b75-b912-b29363b97467)

I believe the problem is that there is no stable version but this message is identical to if the package doesn't exist at all.

The message could perhaps read something like: "Unable to find a stable version of xdebug/xdebug, try installing a specific version."

**Comment by asgrim** [comment]
Dang, I'd addressed this previously to output the message from the Composer resolution before (in #53) but I think that change may have been lost in #83. Thanks for bringing this up, will fix this ASAP, as I agree it's not very clear!

**Comment by derickr** [comment]
Or wait until next week and there will be a 3.4.0 release :-)

**Comment by asgrim** [comment]
Turns out, the changes were still there; this is an edge case where there is no versions for the stability, so Composer doesn't really have much to say regarding dependency resolution; that said, I've improved the messaging by writing out the stability determine in #124 , which will hopefully guide users to understanding the issue better :)
